### ISSUE TITLE
Offline enable

### ISSUE THREAD

**Issue by stdavis** [agrc/recreate#43]
How to store data offline. Do we want to ask the user to cache different areas or just ship the app with all of the data included?

How to deal with Yelp data. Only include if the app is online?

**Comment by brigsz** [comment]
I believe the Mtn Bike Project allows you to download a section of the map, I don't think it ships with all the data included

**Comment by stdavis** [comment]
@brigsz So do you think adding a download button to the details map (the map that shows the actual trail linework) would suffice? So the user would download the map for one trail at a time? Something like this?
![image](https://user-images.githubusercontent.com/1326248/43961530-7486db80-9c72-11e8-8d73-45befd69eaa5.png)

**Comment by brigsz** [comment]
Well, no harm in that being a first step. I think I like the idea

On Aug 10, 2018, at 7:53 AM, Scott Davis <notifications@github.com> wrote:

@brigsz <https://github.com/brigsz> So do you think adding a download
button to the details map (the map that shows the actual trail linework)
would suffice? So the user would download the map for one trail at a time?
Something like this?
[image: image]
<https://user-images.githubusercontent.com/1326248/43961530-7486db80-9c72-11e8-8d73-45befd69eaa5.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/recreate/issues/43#issuecomment-412089090>, or mute
the thread
